url: https://y7kim.github.io
baseurl: 

# Site settings
title: Mylo Ryn
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact info.
author: Mylo Ryn
email: myloryn@riseup.net
phone: "+9785476792"

contact_template: >-
  Hi Mylo, I saw your website and would like to book
  a GOLD/DIAMIND/TITANIUM theme at LOCATION on __ for __ hours.

# Team names, titles and social links
people:
- name: Violet Rollergirl
  pic: violet_square
  position: Pro-Submissive
  social:
    - title: link
      url: https://violetrollergirl.com
    - title: twitter
      url: https://bsky.app/profile/violetrollergirl.com
    - title: heart
      url: https://violetrollergirl.tryst.link

- name: Big Bear 
  pic: big_bear_square
  position: Top Bear
  social:
    - title: link
      url: https://onlyfans.com/bigbear4cuddles
    - title: twitter
      url: https://bsky.app/profile/bigbear4cuddles.bsky.social
    - title: instagram
      url: https://www.instagram.com/bigbearforcuddles

- name: Legolas "Lego" GoldenEar
  pic: lego_square
  position: Canine Familiar 
  social:
    - title: instagram
      url: https://www.instagram.com/lego.and.mouse


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: heart
    url: https://mylo-ryn.tryst.link
  - title: twitter
    url: https://bsky.app/profile/mylo-ryn.com

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
